
[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
decorations = "full"
dynamic_title = true
opacity = 0.8
startup_mode = "Windowed"

[window.dimensions]
columns = 84
lines = 24

[window.padding]
x = 10
y = 10

[general]
live_config_reload = true
import = ["/home/moritz/.config/alacritty/colors.toml", "/home/moritz/.config/alacritty/fonts.toml"]
