#! /usr/bin/env bash

if [[ -z $STOW_FOLDERS ]]; then
    export STOW_FOLDERS="bin,nvim,tmux,zsh,alacritty"
fi

if [[ -z $DOTFILES ]]; then
    export DOTFILES=$HOME/Dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
